import Head from 'next/head'
import { useState } from 'react';
import styles from '@/styles/Home.module.css'

export default function Home(props) {
  let [prompt, setPrompt] = useState("");
  let [isLoading, setIsLoading] = useState(false);
  let [result, setResult] = useState("");

  const handlePromptChange = (e) => {
    setPrompt(e.target.value);
  };
  const handleSubmitPromptBtnClicked = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    fetch("/api/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt: prompt,
      }),
    })
      .then((res) => res.text())
      .then((text) => {
        setResult(text); 
        setIsLoading(false);
      });
  };
  return (
    <>
      {props.user ? (
        <>
         <Head>
        <title>ChatGPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-screen flex flex-col justify-between bg-neutral-800">
          
          {
            result !="" 
            ? 
            <div>
              <div className='bg-neutral-600 border-y border-gray-500 p-4'>
                <h1 className='text-lg font-bold mb-2'>Me:</h1>
                <p className='my-2'>{prompt}</p>
              </div>
              <div className='bg-neutral-800 border-y border-gray-500 p-4'>
                <h1 className='text-lg font-bold mb-2'>AI:</h1>
                <p className='my-2'>{result}</p>
                </div>
              </div> : <div></div>}
          <form className='w-screen flex mx-auto justify-center mb-4'>
            <input className="w-11/12 py-2 px-3 outline-none rounded-md border border-gray-500 focus:border-gray-300 hover:border-gray-300 bg-border-gray-600 mx-2" type="text" value={prompt} onChange={handlePromptChange}/>
            <button className="bg-gray-600 px-3 py-2 rounded-md border border-gray-500 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300" onClick={handleSubmitPromptBtnClicked}>Submit</button>
          </form>
        </div>
      </main>
        </>
        ) : (
          <>
          <Head>
        <title>ChatGPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen flex flex-col justify-center items-center'>
          <button className="border rounded-md border-gray-300 py-2 px-4" onClick={props.signIn}>Sign In</button>
          </main>
          </>
        )}
    </>
  )
}
